# Generated by Django 4.1.3 on 2022-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="newEmp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=300)),
                ("email", models.CharField(max_length=300)),
                ("phone", models.IntegerField()),
                ("message", models.TextField()),
            ],
        ),
    ]
